# -*- coding: utf-8 -*-
"""seaborn

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hUs7T5xv9BXgVv8mvnt33O_HCXYI27eO
"""

import seaborn as sns

df=sns.load_dataset("tips")
df.head()

"""1.For Continous Features: Heatmap, Pairplot, Distplot,boxplot,violinplot

2.For Categorical Features: Countplot, Barplot, boxplot,violinplot

Boxplot and violinplot-one categorical variable(optional i.e can be categorical or umericn) and one continous(must) variable

under facetgrid-must be categorical and under map -can be any
x=sns.FacetGrid(df,row="smoker",col="time").map(plt.scatter,'smoker','tip')
"""

# for Continous Features

df.corr()

sns.heatmap(df.corr())

sns.pairplot(df)

sns.pairplot(df, hue="smoker")

sns.distplot(df['total_bill'])

#for Categorical Features

df.head()

sns.countplot('smoker',data=df)

sns.countplot('sex',data=df)

sns.barplot(x='total_bill', y='sex', data=df)

sns.barplot(x='smoker',y='total_bill',data=df)

sns.boxplot(x="smoker" ,y="total_bill",data=df)

sns.boxplot(x="size", y="tip",data=df)

sns.violinplot(x="size",y="total_bill",data=df)

import matplotlib.pyplot as plt

x=sns.FacetGrid(df,row="smoker",col="time").map(plt.scatter,'smoker','tip')